DROP TABLE IF EXISTS W_USER;
CREATE TABLE W_USER (
    USER_PID			INT NOT NULL auto_increment	COMMENT '사용자PK ID', 
	USER_UID			VARCHAR(50) NOT NULL		COMMENT '사용자ID(이메일)',
    PASSWORD			VARCHAR(50) NOT NULL 		COMMENT '비밀번호',
    NICKNAME			VARCHAR(50) DEFAULT NULL 		COMMENT '별명',
    BIRTH_DATE			VARCHAR(50) DEFAULT NULL	COMMENT '생년월일',
    USER_PHONE			VARCHAR(50) NOT NULL 		COMMENT '사용자전화번호',
    USER_SCHOOL			VARCHAR(50) DEFAULT NULL 	COMMENT '학교',
    USER_TYPE 			VARCHAR(50) DEFAULT NULL 		COMMENT '사용자 타입',
    PRIMARY KEY (USER_PID)
)CHARSET=utf8;